runtime: python39
service: backend  # Nombre del servicio para el backend

entrypoint: gunicorn -b :$PORT app:app

handlers:
  # Ruta para manejar los archivos estáticos (si tienes)
  - url: /static
    static_dir: static

  # Ruta para manejar archivos en la carpeta 'data'
  - url: /data
    static_dir: data

  # Rutas para manejar archivos en la carpeta 'instance' (si es necesario)
  - url: /instance
    static_dir: instance

  # Todas las demás rutas serán manejadas por Flask
  - url: /.*
    script: auto
